set -g @plugin 'vaaleyard/tmux-dotbar'

set -g @tmux-dotbar-bg default
set -g @tmux-dotbar-fg "#c9c7cd"
set -g @tmux-dotbar-fg-current "#c9c7cd"
set -g @tmux-dotbar-fg-session "#9399b2"
set -g @tmux-dotbar-fg-prefix "#cba6f7"

set -g pane-border-style fg="#313134",bg=default

set -g pane-active-border-style fg="#444448",bg=default

set -g @tmux-dotbar-right true
set -g @tmux-dotbar-position bottom

set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
