set -g @plugin 'fabioluciano/tmux-powerkit'
# Basic configuration
set -g @powerkit_separator_style "rounded"
set -g @powerkit_plugins "datetime,battery,cpu,memory,git,hostname"
# set -g @powerkit_theme "catppuccin"
# set -g @powerkit_theme_variant "mocha"
# set -g @powerkit_theme "tokyo-night"
# set -g @powerkit_theme_variant "night"
# set -g @powerkit_theme "dracula"
# set -g @powerkit_theme_variant "dark"
# set -g @powerkit_theme "ayu"

set -g @powerkit_theme "abyss"
# set -g @powerkit_theme "everforest"

set -g @powerkit_theme_variant "dark"
set -g @powerkit_transparent "true"
