-- https://github.com/MariaSolOs/dotfiles/blob/main/.config/nvim/lua/icons.lua
local M = {}

--- Diagnostic severities.
M.diagnostics = {
  ERROR = "",
  WARN = "",
  HINT = "",
  INFO = "",
}

--- For folding.
M.arrows = {
  right = "",
  left = "",
  up = "",
  down = "",
  r_chev = ">",
}

--- LSP symbol kinds.
M.symbol_kinds = {
  Array = "󰅪",
  Class = "",
  Color = "󰏘",
  Constant = "󰏿",
  Constructor = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "󰜢",
  File = "󰈙",
  Folder = "󰉋",
  Function = "󰆧",
  Interface = "",
  Keyword = "󰌋",
  Method = "󰆧",
  Module = "",
  Operator = "󰆕",
  Property = "󰜢",
  Reference = "󰈇",
  Snippet = "",
  Struct = "",
  Text = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "󰀫",
}

--- Shared icons that don't really fit into a category.
M.misc = {
  bug = "",
  ellipsis = "…",
  git = "",
  search = "",
  vertical_bar = "│",
  dashed_bar = "┊",
}

M.kind_icons = {
  Array = " 󰅪 ",
  BlockMappingPair = " 󰅩 ",
  Boolean = "  ",
  BreakStatement = " 󰙧 ",
  Call = " 󰃷 ",
  CaseStatement = " 󰨚 ",
  Class = "  ",
  Color = "  ",
  Constant = "  ",
  Constructor = " 󰆧 ",
  ContinueStatement = "  ",
  Copilot = "  ",
  Declaration = " 󰙠 ",
  Delete = " 󰩺 ",
  DoStatement = " 󰑖 ",
  Element = " 󰅩 ",
  Enum = "  ",
  EnumMember = "  ",
  Event = "  ",
  Field = "  ",
  File = "  ",
  Folder = "  ",
  ForStatement = "󰑖 ",
  Function = " 󰆧 ",
  GotoStatement = " 󰁔 ",
  Identifier = " 󰀫 ",
  IfStatement = " 󰇉 ",
  Interface = "  ",
  Keyword = "  ",
  List = " 󰅪 ",
  Log = " 󰦪 ",
  Lsp = "  ",
  Macro = " 󰁌 ",
  MarkdownH1 = " 󰉫 ",
  MarkdownH2 = " 󰉬 ",
  MarkdownH3 = " 󰉭 ",
  MarkdownH4 = " 󰉮 ",
  MarkdownH5 = " 󰉯 ",
  MarkdownH6 = " 󰉰 ",
  Method = " 󰆧 ",
  Module = " 󰅩 ",
  Namespace = " 󰅩 ",
  Null = " 󰢤 ",
  Number = " 󰎠 ",
  Object = " 󰅩 ",
  Operator = "  ",
  Package = " 󰆧 ",
  Pair = " 󰅪 ",
  Property = "  ",
  Reference = "  ",
  Regex = "  ",
  Repeat = " 󰑖 ",
  Return = " 󰌑 ",
  RuleSet = " 󰅩 ",
  Scope = " 󰅩 ",
  Section = " 󰅩 ",
  Snippet = "  ",
  Specifier = " 󰦪 ",
  Statement = " 󰅩 ",
  String = "  ",
  Struct = "  ",
  SwitchStatement = " 󰨙 ",
  Table = " 󰅩 ",
  Terminal = "  ",
  Text = " 󰀬 ",
  Type = "  ",
  TypeParameter = "  ",
  Unit = "  ",
  Value = "  ",
  Variable = "  ",
  WhileStatement = " 󰑖 ",
}

M.lsp_kinds = {
  Namespace = "󰌗",
  Text = "󰉿",
  Method = "󰆧",
  Function = "󰆧",
  Constructor = "",
  Field = "󰜢",
  Variable = "󰀫",
  Class = "󰠱",
  Interface = "",
  Module = "",
  Property = "󰜢",
  Unit = "󰑭",
  Value = "󰎠",
  Enum = "",
  Keyword = "󰌋",
  Snippet = "",
  Color = "󰏘",
  File = "󰈚",
  Reference = "󰈇",
  Folder = "󰉋",
  EnumMember = "",
  Constant = "󰏿",
  Struct = "󰙅",
  Event = "",
  Operator = "󰆕",
  TypeParameter = "󰊄",
  Table = "",
  Object = "󰅩",
  Tag = "",
  Array = "[]",
  Boolean = "",
  Number = "",
  Null = "󰟢",
  String = "󰉿",
  Calendar = "",
  Watch = "󰥔",
  Package = "",
  Copilot = "",
  Codeium = "",
  TabNine = "",
}

local icons_spaced = {}
for key, value in pairs(M.kind_icons) do
  icons_spaced[key] = value .. " "
end
-- 带空格的图标
M.kind_icons_spaced = icons_spaced

return M
