-- 在浏览器中预览 markdown
return {
  {
    "MeanderingProgrammer/render-markdown.nvim",
    opts = {},
    enabled = false,
    dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" },
    config = function()
      -- require("render-markdown").setup({
      --   heading = {
      --     enabled = true,
      --     sign = true,
      --     position = "overlay",
      --     icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
      --     signs = { "󰫎 " },
      --     width = "full",
      --     left_margin = 0,
      --     left_pad = 0,
      --     right_pad = 0,
      --     min_width = 0,
      --     border = false,
      --     border_virtual = false,
      --     border_prefix = false,
      --     above = "▄",
      --     below = "▀",
      --     backgrounds = {
      --       "RenderMarkdownH1Bg",
      --       "RenderMarkdownH2Bg",
      --       "RenderMarkdownH3Bg",
      --       "RenderMarkdownH4Bg",
      --       "RenderMarkdownH5Bg",
      --       "RenderMarkdownH6Bg",
      --     },
      --     foregrounds = {
      --       "RenderMarkdownH1",
      --       "RenderMarkdownH2",
      --       "RenderMarkdownH3",
      --       "RenderMarkdownH4",
      --       "RenderMarkdownH5",
      --       "RenderMarkdownH6",
      --     },
      --   },
      --   code = {
      --     enabled = true,
      --     sign = true,
      --     style = "full",
      --     position = "left",
      --     language_pad = 0,
      --     disable_background = { "diff" },
      --     width = "full",
      --     left_margin = 0,
      --     left_pad = 0,
      --     right_pad = 0,
      --     min_width = 0,
      --     border = "thin",
      --     above = "▄",
      --     below = "▀",
      --     highlight = "RenderMarkdownCode",
      --     highlight_inline = "RenderMarkdownCodeInline",
      --   },
      -- })
    end,
  },
}
